---
title: "Group Project"
author: "Blake Lucas & Brendan Davis"
---

# Project Description
{description of project}

+ Iouzipcodes
```{r, include=FALSE, echo=FALSE}
library(gtools) #used for binomial search of zip code lat/lon
library(dplyr)
library(ggplot2)
```
```{r, echo=FALSE}

site <- "iouzipcodes2015.csv"
iouZips <- read.csv(file = site)
head(iouZips, n = 1) # show first five rows

#number of iouZips by state
iouZips %>% 
	group_by(state) %>% 
	summarise(count = n()) %>% 
	ggplot(aes(x = reorder(state,(-count)), y = count)) + 
		geom_bar(stat = 'identity')
```

+ NonIouzipcodes
```{r, echo=FALSE}
site <- "noniouzipcodes2015.csv"
nonIouZips <- read.csv(file = site)
head(nonIouZips, n = 1) # show first five rows

#number of noniouZips by state
nonIouZips %>% 
	group_by(state) %>% 
	summarise(count = n()) %>% 
	ggplot(aes(x = reorder(state,(-count)), y = count)) + 
		geom_bar(stat = 'identity')
```

+ ZipCode latitude and longitation
```{r, echo=FALSE}
site <- "zipcodelatlon.csv"
zipsLocation <- read.csv(file = site)
head(zipsLocation, n = 5) # show first five rows

#These two functions allow you to search a zipcodes Latitude, first is a helper function
subFun <- function(x) {
  return (zipsLocation$ZIP[[x]])
}
#zipsLocation$LAT[[binsearch(fun = subFun, range = c(1,length(zipsLocation)), target = 602)$where]]
findLat <- function(zip)
{
  i <- zipsLocation$LAT[[binsearch(fun = subFun, range = c(1,nrow(zipsLocation)), target = zip)$where]]
  return (i)
} 

#(fun = subFun, range = c(1,nrow(zipsLocation)), target = 1010)$where

iouZipsLoc <- 
  mutate(iouZips, lat = findLat(zip))
head(iouZipsLoc)

#TODO: Exlpore heatmap possibility

#TODO: Get a hypothesis for our data before we get too far
```

